### ISSUE TITLE
Tasks division

### ISSUE THREAD

**Issue by Reem-lab** [Nicolaswg/Capstone_Pokemon_Api#21]
##  Link to my GitHub project
 - https://github.com/Nicolaswg/Capstone_Pokemon_Api/projects/1

 - There are Two people Working on this project 
     - Student B :  @Reem-lab 
     - Student A :  @Nicolaswg

**Comment by julie-ify** [comment]
## Hi team,

Good job so far!

## Highlight!
- Good job creating the project and the cards ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

- [x] Let's assign tasks so that we know which teammate is assigned to student A and who will be working as student B. Watch this loom [video](https://www.loom.com/share/dc8b3b016ab54d06a899d635b8a20125) I created to see how you can assign tasks. 😉. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BrianSammit** [comment]
# STATUS: APROVED :green_circle: :clap: 

Hello @Reem-lab, and @Nicolaswg , 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
